<?php

return array (
  'version' => '5.6.4',
  'title' => 'Partners',
  'type' => 'partners',
  'id' => '620d35fb1b3e6',
  'updated' => 1645032988,
  'columns' => 
  array (
    '620d35d60f9db4' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '130',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '110',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '620d35d60f9db4',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'name' => 'title',
    ),
    '620d35ebb1eb84' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Partner website',
      'width' => '',
      'width_unit' => '%',
      'field' => 'partner_url',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '620d35ebb1eb84',
    ),
    'taxonomy-partnercategories' => 
    array (
      'type' => 'taxonomy-partnercategories',
      'label' => 'Partner categories',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'taxonomy-partnercategories',
    ),
    '620d360ec8b438' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '125',
      'width_unit' => 'px',
      'use_icon' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '620d360ec8b438',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);